{% set name = "peewee" %}
{% set version = "3.9.5" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "f0249be468e3b119a8ad83f686e7fe161303197e0534e3cdff8fa5a5417c01a5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.22.1
    - msinttypes  # [win]
    - sqlite
  run:
    - python

test:
  imports:
    - playhouse
    - peewee

about:
  home: https://github.com/coleifer/peewee/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A little ORM'
  dev_url: https://github.com/coleifer/peewee/
  doc_url: http://docs.peewee-orm.com/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - dharhas
