{% set name = "peewee" %}
{% set version = "3.1.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "0241da57d57ab02ecc87e85a4422fed828d1e02f69744e21ec609821cbb295ec" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:

  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - cython >=0.22.1

  run:
    - python

test:
  imports:
    - playhouse
    - peewee

about:
  home: https://github.com/coleifer/peewee/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A little ORM'
  dev_url: https://github.com/coleifer/peewee/
  doc_url: http://docs.peewee-orm.com/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - dharhas
