schema_version: 1

context:
  name: peewee
  version: 3.18.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 77a54263eb61aff2ea72f63d2eeb91b140c25c1884148e28e4c0f7c4f64996a0

build:
  number: 1
  script: python -m pip install . -vv --no-build-isolation --no-deps

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - cython >=0.22.1
    - if: win
      then: msinttypes
    - sqlite
    - setuptools
    - wheel
  run:
    - python

tests:
  - python:
      imports:
        - playhouse
        - peewee
      pip_check: true

about:
  license: MIT
  license_file: LICENSE
  summary: A little ORM
  homepage: https://github.com/coleifer/peewee/
  repository: https://github.com/coleifer/peewee/
  documentation: http://docs.peewee-orm.com/en/latest/

extra:
  recipe-maintainers:
    - dharhas
    - synapticarbors
