travis:
  secure:
    BINSTAR_TOKEN: IV06TAzCei4wAZMCyq4MfF+A3Mv+ppsc1msrXYNENOLv9mL872lABW74aonHI3QSc38OL1ggooPrRVpPSVkLHqXYCUtL4BArSZI7w/6DO4RaQxnWjNtPnav5mGAU1wLmYjfvlcm1dTxsUF0eKlK0ExBOYYGcAfj4RYt/XlVRbl6yRokR47uabk9YRgESB0zQPz7ZiE/rp3d9pQDhMB0LDpHlmtOaB9p+tJBJ4JXxip8Mtw51yszrCjLUraOjBK89NdLChKTiWg/80svnpi/KLvMHwu/cFidiWzFLZlLk9M+Wyv/Jb4ZAd87dCegfMorNRs2e6Fnbhf+XuKvTsEpRD/yYbLcKtrdo+p8oynRWCgdjfjVMJOchXpqyXdAF/B0dvz5wKFpPJRTVS2slVun/+3Tk3oHXSRcmuQh20yRcKmxCsmOUgesMPdIalGl7mMb5PABP7dNfei3M3FCzg/O5nDCcsSSGBZ3ibtPh7y3T0UZtjM+N6tOJXTH+1e6a6WDBUVCiG40ycZWcBhyUf/sjA14UJcS14IZqabDCI69GRmedfCvheKI3/CickGfqPfW1L9iCmnXz5HjyfDhYTHUqX6Dlh4kIM9bUWEK7o713LMuJikin0YnIKDn8ijLb97FyBZaDHrknUcx7JA0Z3uEqCgXY1kScbnJsbCIo8UfATpw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
